title: "Easy Topdown Controller 2D"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  "Buy on the Asset Store":
    - "https://assetstore.unity.com"

aux_links_new_tab: true

heading_anchors: false
