title: "Ultimate Topdown Controller 2D"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  "Get it in the Unity Asset Store":
    - "https://assetstore.unity.com"

aux_links_new_tab: true

heading_anchors: false
